-- Fix for missing competitive exam table in Supabase
-- Run this in Supabase SQL Editor for the live project.

create table if not exists public.competitive_exam_materials (
  material_id bigint generated by default as identity primary key,
  title text not null,
  exam_name text not null,
  format_id bigint not null references public.content_formats(format_id),
  instructor_name text,
  duration_lessons text,
  chapter_number integer,
  file_url text not null,
  created_at timestamp with time zone default now()
);

alter table public.competitive_exam_materials add column if not exists chapter_number integer;

-- Optional card background image shown on the homepage "Prep for competitive" cards
alter table public.competitive_exam_materials add column if not exists bg_thumbnail_url text;

-- This app uses the public anon key for admin operations, so the table must allow
-- insert/select/update/delete from the public role while the project is in MVP mode.
alter table public.competitive_exam_materials enable row level security;

drop policy if exists "competitive_exam_materials_public_all" on public.competitive_exam_materials;

create policy "competitive_exam_materials_public_all"
on public.competitive_exam_materials
for all
using (true)
with check (true);

-- Optional: if you want to check the table immediately
select * from public.competitive_exam_materials order by material_id desc limit 20;

-- Insert a sample record
insert into public.competitive_exam_materials
(title, exam_name, format_id, instructor_name, duration_lessons, chapter_number, file_url)
values
('BPSC Prelims 2025 Notes', 'BPSC', 1, 'Exam Mentor', '12 chapters', 1, 'https://drive.google.com/uc?export=download&id=YOUR_FILE_ID');
