-- Supabase SQL schema for Adhyayan Parevartan
-- Run this in Supabase SQL Editor after creating the project.

create table if not exists roles (
  role_id bigint generated by default as identity primary key,
  role_name text unique not null
);

create table if not exists users (
  user_id bigint generated by default as identity primary key,
  role_id bigint not null references roles(role_id),
  full_name text not null,
  email text unique not null,
  password_hash text not null,
  google_oauth_id text,
  class_number integer,
  board text,
  streak_days integer default 0,
  xp_points integer default 0,
  is_approved integer default 0,
  created_at timestamp with time zone default now()
);

create table if not exists subjects (
  subject_id bigint generated by default as identity primary key,
  subject_name text not null,
  class_number integer not null
);

create table if not exists content_formats (
  format_id bigint generated by default as identity primary key,
  format_name text unique not null
);

create table if not exists learning_materials (
  material_id bigint generated by default as identity primary key,
  subject_id bigint not null references subjects(subject_id) on delete cascade,
  format_id bigint not null references content_formats(format_id),
  title text not null,
  description text,
  file_url text not null,
  duration_lessons text,
  instructor_name text,
  chapter_number integer,
  created_at timestamp with time zone default now()
);

-- MIGRATION: run this if learning_materials already exists without chapter_number
-- (safe/no-op on a fresh install since the create table above already has it)
alter table learning_materials add column if not exists chapter_number integer;

create table if not exists quizzes (
  quiz_id bigint generated by default as identity primary key,
  title text not null,
  class_number integer not null,
  subject_id bigint references subjects(subject_id) on delete set null,
  chapter_name text,
  subject_icon text,
  questions_json jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists competitive_exam_materials (
  material_id bigint generated by default as identity primary key,
  title text not null,
  exam_name text not null,
  format_id bigint not null references content_formats(format_id),
  instructor_name text,
  duration_lessons text,
  chapter_number integer,
  file_url text not null,
  created_at timestamp with time zone default now()
);

alter table competitive_exam_materials add column if not exists chapter_number integer;

create table if not exists notifications (
  notification_id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  created_at timestamp with time zone default now()
);

create table if not exists site_content (
  page_key text primary key,
  title text,
  content text,
  updated_at timestamp with time zone default now()
);

insert into roles (role_name) values ('Admin') on conflict (role_name) do nothing;
insert into roles (role_name) values ('Teacher') on conflict (role_name) do nothing;
insert into roles (role_name) values ('Student') on conflict (role_name) do nothing;

insert into content_formats (format_name) values ('E-Book') on conflict (format_name) do nothing;
insert into content_formats (format_name) values ('Audio Book') on conflict (format_name) do nothing;
insert into content_formats (format_name) values ('Video Content') on conflict (format_name) do nothing;

-- Google Play review account. Run this after the schema is created.
insert into users (role_id, full_name, email, password_hash, class_number, board, is_approved)
select role_id, 'Rahul Kumar', 'rahul@example.com', 'password123', 9, 'CBSE', 1
from roles where role_name = 'Student'
on conflict (email) do update set
  role_id = excluded.role_id,
  password_hash = excluded.password_hash,
  class_number = excluded.class_number,
  board = excluded.board,
  is_approved = excluded.is_approved;

-- Optional: create a storage bucket for uploaded files
-- In Supabase Dashboard: Storage > New bucket > name: learning_materials
