-- Supabase SQL schema for Adhyayan Parevartan
-- Run this in Supabase SQL Editor after creating the project.

create table if not exists roles (
  role_id bigint generated by default as identity primary key,
  role_name text unique not null
);

create table if not exists users (
  user_id bigint generated by default as identity primary key,
  role_id bigint not null references roles(role_id),
  full_name text not null,
  email text unique not null,
  password_hash text not null,
  google_oauth_id text,
  class_number integer,
  board text,
  streak_days integer default 0,
  xp_points integer default 0,
  is_approved integer default 0,
  created_at timestamp with time zone default now()
);

create table if not exists subjects (
  subject_id bigint generated by default as identity primary key,
  subject_name text not null,
  class_number integer not null
);

create table if not exists content_formats (
  format_id bigint generated by default as identity primary key,
  format_name text unique not null
);

create table if not exists learning_materials (
  material_id bigint generated by default as identity primary key,
  subject_id bigint not null references subjects(subject_id) on delete cascade,
  format_id bigint not null references content_formats(format_id),
  title text not null,
  description text,
  file_url text not null,
  thumbnail_url text,
  duration_lessons text,
  instructor_name text,
  chapter_number integer,
  created_at timestamp with time zone default now()
);

-- MIGRATION: run this if learning_materials already exists without chapter_number
-- (safe/no-op on a fresh install since the create table above already has it)
alter table learning_materials add column if not exists chapter_number integer;

-- MIGRATION: run this if learning_materials already exists without thumbnail_url
-- (safe/no-op on a fresh install since the create table above already has it)
alter table learning_materials add column if not exists thumbnail_url text;

create table if not exists quizzes (
  quiz_id bigint generated by default as identity primary key,
  title text not null,
  class_number integer not null,
  subject_id bigint references subjects(subject_id) on delete set null,
  chapter_name text,
  subject_icon text,
  questions_json jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists competitive_exam_materials (
  material_id bigint generated by default as identity primary key,
  title text not null,
  exam_name text not null,
  format_id bigint not null references content_formats(format_id),
  instructor_name text,
  duration_lessons text,
  chapter_number integer,
  file_url text not null,
  created_at timestamp with time zone default now()
);

alter table competitive_exam_materials add column if not exists chapter_number integer;

create table if not exists notifications (
  notification_id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  created_at timestamp with time zone default now()
);

create table if not exists site_content (
  page_key text primary key,
  title text,
  content text,
  updated_at timestamp with time zone default now()
);

-- Per-student lesson progress ("Continue learning" card + resume where you left off).
-- last_page / total_pages / pages_completed drive page-based progress for PDF e-books;
-- last_position_sec is the resume point for video/audio.
create table if not exists student_progress (
  progress_id bigint generated by default as identity primary key,
  student_id bigint not null references users(user_id) on delete cascade,
  material_id bigint not null references learning_materials(material_id) on delete cascade,
  completion_percentage integer not null default 0
    constraint student_progress_completion_percentage_range check (completion_percentage between 0 and 100),
  is_completed boolean not null default false,
  last_page integer default 1,
  total_pages integer default 0,
  pages_completed integer default 0,
  last_position_sec integer,
  duration_sec integer,
  last_accessed_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint student_progress_student_material_key unique (student_id, material_id)
);

-- MIGRATION: for a student_progress table created by an older version of this file.
-- Additive and safe to re-run. (The live project's older table used integer ids and
-- was upgraded with exactly these changes; see the RLS note below for access rules.)
alter table student_progress add column if not exists last_page integer default 1;
alter table student_progress add column if not exists total_pages integer default 0;
alter table student_progress add column if not exists pages_completed integer default 0;
alter table student_progress add column if not exists last_position_sec integer;
alter table student_progress add column if not exists duration_sec integer;
alter table student_progress add column if not exists last_accessed_at timestamp with time zone not null default now();
create unique index if not exists student_progress_student_material_key on student_progress (student_id, material_id);

-- completion_percentage must be 0..100 (enforced for new writes right away; old rows are validated after).
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.student_progress'::regclass
      and conname = 'student_progress_completion_percentage_range'
  ) then
    alter table student_progress
      add constraint student_progress_completion_percentage_range
      check (completion_percentage between 0 and 100) not valid;
  end if;
  begin
    alter table student_progress validate constraint student_progress_completion_percentage_range;
  exception when check_violation then
    raise notice 'Some existing rows have completion_percentage outside 0..100; fix them and re-run to validate the check.';
  end;
end $$;

-- Fast "most recently opened lesson" lookups.
create index if not exists student_progress_student_recent_idx
  on student_progress (student_id, last_accessed_at desc);

-- Keep updated_at fresh on every UPDATE.
create or replace function student_progress_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgrelid = 'public.student_progress'::regclass
      and tgname = 'student_progress_set_updated_at' and not tgisinternal
  ) then
    create trigger student_progress_set_updated_at
      before update on student_progress
      for each row execute function student_progress_set_updated_at();
  end if;
end $$;

-- RLS / access: mirrors the live project.
-- IMPORTANT: the app signs in with its own users table and only the anon key, so
-- auth.uid() is always NULL and these policies cannot be per-student. They are open
-- to every holder of the anon key (read, insert, update; no delete). Replace them with
-- per-student policies (e.g. student_id = (auth.jwt() ->> 'app_user_id')::bigint) once
-- logins are verified server-side (Edge Function + JWT or Supabase Auth).
alter table student_progress enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'student_progress'
                 and policyname = 'Users can read own progress') then
    create policy "Users can read own progress" on student_progress for select to public using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'student_progress'
                 and policyname = 'Users can insert own progress') then
    create policy "Users can insert own progress" on student_progress for insert to public with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'student_progress'
                 and policyname = 'student_progress_anon_update') then
    create policy student_progress_anon_update on student_progress for update to anon using (true) with check (true);
  end if;
end $$;

insert into roles (role_name) values ('Admin') on conflict (role_name) do nothing;
insert into roles (role_name) values ('Teacher') on conflict (role_name) do nothing;
insert into roles (role_name) values ('Student') on conflict (role_name) do nothing;

insert into content_formats (format_name) values ('E-Book') on conflict (format_name) do nothing;
insert into content_formats (format_name) values ('Audio Book') on conflict (format_name) do nothing;
insert into content_formats (format_name) values ('Video Content') on conflict (format_name) do nothing;

-- Google Play review account. Run this after the schema is created.
insert into users (role_id, full_name, email, password_hash, class_number, board, is_approved)
select role_id, 'Rahul Kumar', 'rahul@example.com', 'password123', 9, 'CBSE', 1
from roles where role_name = 'Student'
on conflict (email) do update set
  role_id = excluded.role_id,
  password_hash = excluded.password_hash,
  class_number = excluded.class_number,
  board = excluded.board,
  is_approved = excluded.is_approved;

-- Optional: create a storage bucket for uploaded files
-- In Supabase Dashboard: Storage > New bucket > name: learning_materials
